    
<?php
$url="http://localhost:8983/solr/biblio/select?facet.field=institution&df=institution&distrib=false&f.institution.facet.mincount=1&fl=uid&start=0&fsv=true&f.institution.facet.limit=-1&facet=true&indent=true&q.op=OR&q=*%3A*&wt=json"; 
$urlcountry="http://localhost:8983/solr/biblio/select?facet.field=countrycode&df=countrycode&distrib=false&f.countrycode.facet.mincount=1&fl=uid&start=0&fsv=true&f.countrycode.facet.limit=-1&facet=true&indent=true&q=*%3A*&wt=json"; 
$urlresources="http://localhost:8983/solr/biblio/select?facet.field=component&df=component&distrib=false&f.component.facet.mincount=1&fl=uid&start=0&fsv=true&f.component.facet.limit=-1&facet=true&indent=true&q.op=OR&q=*%3A*&wt=json";
$content = file_get_contents($url);
$contentcountry = file_get_contents($urlcountry);
$contentresources = file_get_contents($urlresources);
$objeto = json_decode($content, true);
$objetocountry = json_decode($contentcountry, true);
$objectresources = json_decode($contentresources, true, \JSON_UNESCAPED_UNICODE);
$total = $objeto['response']['numFound'];
$institution = $objeto['facet_counts']['facet_fields']['institution'];
$objetocountry = $objetocountry['facet_counts']['facet_fields']['countrycode'];
$resources = $objectresources['facet_counts']['facet_fields']['component'];
$totalInst = 0; $countries = array(['Country']); $cont = 0; $resourcesTotal = new stdClass(); $class=""; 
foreach($institution as $inst)
{
  if(is_string($inst))
  $totalInst++;
}

foreach($objetocountry as $contr)
{
  if(is_string($contr))
  array_push($countries, array($contr)); 
}
$countries=array_unique($countries, SORT_REGULAR);

foreach ($resources as $r){
  if (is_string($r))
  {
    $name =$r;
  } elseif(is_integer($r)){
    $resourcesTotal->$name=$r;
  }

}

switch (count($resources)/2) {
  case '2':
    $class="6";
    break;
  case '3':
    $class="4";
    break;
  case '4':
    $class="3";
    break;
  case '5':
    $class="2";
    break;
  
  default:
    $class="12";
    break;
}


?>



<div class="row">
  <div class="col-lg-8">
    <div class="institutions-map">
    <h4>Mapa de ubicación de recursos</h4>
      <div id="regions_div" ></div>
    </div>
  </div>
  <div class="col-lg-4 button-section">
    <ul>
      <li class="resources-specialized"><a href="<?=$this->url('content-page', ['page' => 'specialized']) ?>">Recursos especializados</a></li>
      <li class="resources-knowledge"><a href="<?=$this->url('content-page', ['page' => 'knowledge']) ?>">Recursos de conocimiento</a></li>
      <li class="resources-information"><a href="<?=$this->url('content-page', ['page' => 'information']) ?>">Comparta sus recursos de información</a></li>
    </ul>
  </div>

</div>




<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
    <script type="text/javascript">

    var x = document.querySelectorAll(".number");
    var arrayCountries = <?php echo json_encode($countries)?>;
        google.charts.load('current', {
          'packages':['geochart'],
        });
      google.charts.setOnLoadCallback(drawRegionsMap);

    for (var i = 0; i < x.length; i++) {
      automaticCounter(x[i]);
      
    }

    function automaticCounter(value){
        var counter = { var: 0 };
        TweenMax.to(counter, 3, {
          var: value.innerText, 
          onUpdate: function () {
            var number = Math.ceil(counter.var);
            value.innerHTML = number;
          },
    
          ease:Circ.easeOut
        });
    }
        

    function drawRegionsMap() {
      var data = google.visualization.arrayToDataTable(arrayCountries);
      var options = {
        'title': 'Mapa de ubicación de recursos',
            defaultColor: '#2d8dc5',
            datalessRegionColor: '#fbfbfb',
      };
      var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));
      chart.draw(data, options);
      }
       
</script>
