    
<div class="specialized-banner">
    <?=$this->render('header.phtml')?>
</div>
<div class="specialized-title">
    <h2>Directorio de Bibliotecas</h2>
</div>
<div id="directory">
  <div class="row col-md-12">
    <div class="box col-md-4">
      <a href="https://agriperfiles.agri-d.net/display/n29331"> Especialistas de información </a>
    </div>
    <div class="box col-md-4">
      <a href="http://agriperfiles.agri-d.net/individual/n104766"> Redes Nacionales </a>
    </div>
    <div class="box col-md-4">
      <a href="http://agriperfiles.agri-d.net/individual/n120361"> Directorio de bibliotecas </a>
    </div>
  </div>
  <div class="directory-map">
    <h3><a>Mapa</a></h3>
    <div class="col-md-12">
    <iframe src="https://www.google.com/maps/d/embed?mid=1w-9ig7Zv30BR1sL9-ApX3FzQZRg&ehbc=2E312F&z=3" width="1200" height="800px"></iframe>
    </div>
  </div>
</div>





