<?php $this->headTitle($this->translate('FAQs')); ?>
<div class="specialized-banner">
    <?=$this->render('header.phtml')?>
</div>
<div class="specialized-title">
    <h2><?=$this->transEsc('FAQs') ?></h2>
</div>

<div id="frequently_asked">
    <p>Si sus dudas o consulta no fueron totalmente cubiertas, por favor envíenos un correo electrónico a la dirección sidalc@iica.int y con gusto atenderemos su solicitud.</p>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div> ¿Qué es la Alianza SIDALC? </button>
    <div class="content">
        <p>El SIDALC es una alianza internacional de servicios información agrícola, pecuaria, forestal y ambiental, mediante el cual un importante grupo de instituciones de 22 países americanos comparten en red, su información y sus servicios. Creado en 1999, hoy constituye una de las ventanas del conocimiento explicito más importantes de ALC.  La puesta en operación del SIDALC fue posible gracias a una donación de la Fundación Kellogg, al liderazgo técnico que asumieron el IICA y el CATIE y a la participación de una importante cantidad de instituciones nacionales, regionales e internacionales. Para más información acceda el siguiente enlace “Sobre la Alianza SIDALC”</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Qué es la Alianza de Servicios de Información Agropecuaria?</button>
    <div class="content">
        <p>La Alianza de Servicios de Información Agropecuaria es una ventana al conocimiento agrícola generado en América Latina y el Caribe, está compuesta por una MegaBase de datos en agricultura que reúne las mejores bases de datos bibliográficas especializadas en agricultura y ciencias afines, producidas por instituciones nacionales e internacionales, que puedan ser accesadas a través de Internet mediante la dirección web http://www.sidalc.net</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo participar en la Alianza?</button>
    <div class="content">
        <p>Ponemos a disposición los recursos técnicos y humanos para colaborar en todo el proceso, en principio debe enviarnos la dirección del protocolo de intercambio OAI-PMH de su plataforma.    Remitirnos una breve descripción sobre el contenido, temática, dirección, página web en caso de tenerla, responsable y un correo electrónico a donde llegarán las solicitudes de los usuarios, además es importante que su biblioteca y los profesionales que laboran en ella cuenten con un perfil en la plataforma AgriPerfiles.  Cada institución participante será responsable por la calidad, relevancia y actualidad de la información incluida, también por el ofrecimiento de los servicios derivados.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Si mi base de datos no tiene un formato de exportación estándar, que debo enviar para participar?</button>
    <div class="content">
        <p>En caso de que la herramienta que utilizan para gestionar sus recursos de información no cuenta con algún protocolo de intercambio o algún esquema estándar como por ejemplo MARC, Dubli Core, entre otros, puede indicarnos las opciones de exportación con que cuenta la herramienta para determinar la mejor opción.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Qué debo enviar para actualizar mi base de datos?</button>
    <div class="content">
        <p>Si ya está participando en la Alianza de Servicios de Información Agropecuaria, puede enviar el enlace OAI-PMH de su plataforma, en caso de no contar con el protocolo de intercambio, puede enviar en formato mrc, pero si no tienen esos formatos puede indicarnos las opciones de exportación con que cuenta la herramienta para determinar la mejor opción.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo enviar mi base de datos o las actualizaciones?</button>
    <div class="content">
        <p>Los enlaces OAI-PMH puede enviarlos al correo electrónico sidalc@iica.int.</p>
        <p>En cuanto a los archivos exportados puede enviarlos también al correo electrónico sidalc@iica.int, en caso de ser archivo grandes puede utilizar la herramienta WeTransfer (https://wetransfer.com/)</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Con qué frecuencia debo actualizar mi base de datos?</button>
    <div class="content">
        <p>Esto depende del volumen de datos que su institución administre, algunas instituciones realizan este procedimiento una vez al mes, otras cada dos o tres meses. Lo más importante es que los usuarios que acceden la Alianza SIDALC encuentren la información más actualizada, y cortos tiempos de respuesta a sus solicitudes.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Qué es AgriPerfiles?</button>
    <div class="content">
        <p>AgriPerfiles es una iniciativa hemisférica liderada por el IICA para promover una mejor vinculación de los perfiles profesionales de la agricultura y el desarrollo rural y su vinculación con la información relacionada. (https://agriperfiles.agri-d.net/)</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>Si somos miembros de la Alianza SIDALC ¿Cuál es el procedimiento para registrar a mi institución, biblioteca y especialistas de información en AgriPerfiles?</button>    
    <div class="content">
        <p>Las instituciones del sector agropecuario de América Latina y el Caribe que deseen registrar a sus profesionales en la plataforma deben enviar un correo electrónico a agriperfiles@iica.int, solicitando su participación.</p>
        <p>Las bibliotecas que son parte de la Alianza SIDALC cuentan con un perfil, por lo que pueden solicitar la creación de un perfil profesional de sus especialistas de información, además se le dará acceso al perfil para su respectiva actualización, así mismo serán incluidos en el <a href="https://agriperfiles.agri-d.net/display/n120361"> directorio de biblioteca participantes en la Alianza SIDALC </a>y los perfiles profesionales se relacionarán al grupo de la <a href="https://agriperfiles.agri-d.net/display/n29331"> Alianza de Servicios de Información y Documentación de las Américas </a>, pueden enviar la solicitud al correo sidalc@iica.int</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cuál es el procedimiento para ingresar información en el perfil de AgriPerfiles?</button>    
    <div class="content">
        <p>En el siguiente enlace podrá encontrar <a href="https://www.youtube.com/watch?v=uaVajJDwGvc" >un video </a>en el cual se describe el proceso para el ingreso de información. En varios de los campos a ingresar, conforme va introduciendo texto, se despliega información que ya fue ingresada por otro usuario, en caso de que sea información requerida por usted, por favor selecciónela. El perfil del <a href="https://agriperfiles.agri-d.net/display/nip68110" > Dr. Pedro Rocha S. </a>puede ser utilizado como ejemplo para completar su perfil</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Mi institución desea incluir a sus funcionarios profesionales relacionados al sector agropecuario en AgriPerfiles, cuáles son los pasos a seguir?</button>    
    <div class="content">
        <p>Enviar un correo electrónico (agriperfiles@iica.int) solicitando su deseo de registrar a los profesionales de su instituciona en AgriPerfiles.  Luego coordinaremos una reunión para presentar las ventajas de la plataforma y en conjunto definir los siguientes pasos.</p>
        <p>Se solicita definir una o más personas, en coordinación en el departamento de Recursos Humanos, que serán capacitados para registrar y dar seguimiento a los perfiles instruccionales, así mismo se les asignarán los respectivos permisos para la curación y edición.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo cambiar la contraseña para acceder a mi perfil en AgriPerfiles?</button>
    <div class="content">
        <p>Debe enviar un correo electrónico a la dirección agriperfiles@iica.int e indicar que desea reiniciar su contraseña.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cuál es el objetivo de la lista?</button>
    <div class="content">
        <p>El objetivo es intercambiar experiencias, discutir problemas técnicos, establecer o sugerir metodología de trabajo o procedimientos para ser aplicados en las distintas unidades de información.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Quién puede participar en la lista?</button>
    <div class="content">
        <p>Pueden participar coordinaciones nacionales, miembros de la red del SIDALC, bibliotecas agropecuarias, bibliotecarios, documentalistas e informáticos del sector.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo me suscribo o desinscribo de la lista SIDALC?</button>
    <div class="content">
        <p>Según lo que desee realizar, debe enviar un correo electrónico para que automáticamente sea inscrito o desinscrito de la lista.</p>
        <p>Suscribirse: sidalc+subscribe@googlegroups.com</p>
        <p>Desinscribirse: sidalc+unsubscribe@googlegroups.com</p>
        <p>Moderador/Owner: sidalc+owner@googlegroups.com</p>
        <p>Dirección de la página web http://groups.google.com/group/sidalc</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo accedo a las estadísticas de SIDALC y bases de datos individuales?</button>
    <div class="content">
        <p>El primer paso que debemos realizar para acceder las estadísticas es que nos envíe su <strong>cuenta de correo electrónico de gmail </strong>para proceder con el registro en el módulo.</p>
        <p>En la siguiente dirección podrá acceder las estadísticas de la base de datos NOMBRE-BD, http://www.google.com/analytics, debe ingresar su correo electrónico y contraseña de gmail.</p>
        <p>Este <a href="https://www.youtube.com/watch?v=r_1fHqZTZ9E"> video mustra el procedimiento para acceder las estadísticas </a>, mismo que se describe en el siguiente texto:</p>
        <p>En el menú de la izquierda seleccionar la opción [Comportamiento] / [Contenido del sitio] / [Todas las páginas], seguidamente desplegará el contenido general.  Al lado derecho de la pantalla, debajo del gráfico hay espacio para digitar el nombre de su base de datos  NOMBRE-BD y presione [ENTER] o en la imagen de un de la lupa.  En el botón [Seleccionar] podrá encontrar varias opciones que le apoyarán en su análisis.</p>
        <p>Se despliegan las estadísticas para el período seleccionado, el periodo puede ser modificado en la parte superior derecha.</p>
    </div>
    <button type="button" class="faq_collapse"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>¿Cómo agrego la localización de la biblioteca en el mapa?</button>
    <div class="content">
        <p>En el siguiente enlace conocerán el procedimiento para la ubicación: https://www.youtube.com/watch?v=Ewfeh18NIGk (Tomen en cuenta que el sonido está un poco bajo para que le suban el volumen).  El mapa puede ser accedido mediante el título "<a href="https://www.google.com/maps/d/u/0/viewer?msa=0&ll=-5.55071247058112%2C-83.49609400000003&spn=69.243881%2C79.013672&mid=1w-9ig7Zv30BR1sL9-ApX3FzQZRg&z=3"> Bibliotecas Participantes en la Alianza SIDALC </a>"</p>
    </div>
    <button type="button" class="faq_collapse last"><div class="tag"><i class="fa fa-plus" aria-hidden="true"></i></div>Los pasos son los siguientes:</button>
    <div class="content last">
        <ul>
            <li>Para acceder a la edición del mapa deben enviarnos una dirección de correo electrónico de gmail.</li>
            <li>Una vez incorporado con su cuenta de gmail,  se le enviará una invitación a esa cuenta de correo.</li>
            <li>En el correo de invitación encontrará un enlace que le permitirá acceder.</li>
            <li>Presionar el botón EDITAR.</li>
            <li>Ubicar la posición exacta de su biblioteca.</li>
            <li>Con el botón marcador (de color azul) defina la posición exacta de su biblioteca.</li>
            <li>Se habilitará un cuadro de dialogo, en el que debe colocar la información.</li>
            <li>En la parte superior colocar el nombre de la institución y nombre de la biblioteca.</li>
            <li>En el espacio de abajo de ese cuadro escriba el texto "Información sobre la biblioteca". Nosotros nos encargaremos de hacer el enlace a la información contenida en el directorio de bibliotecas.</li>
            <li>En ese mismo cuadro de dialogo, presione el marcador de color azul que se encuentra en la parte superior derecha, luego click al texto "Agregar un icono". Se habilitará un espacio para colocar el siguiente enlace http://www.sidalc.net/misc/alfiler.png. Esto cambiará al marcador del SIDALC.</li>
            <li>Finalmente, en ese mismo cuadro de dialogo, presione ACEPTAR.</li>
            <li>Luego en la parte derecha de su pantalla, presione GUARDAR y FINALIZAR</li>
        </ul>
    </div>
</div>
<script>
    var faq_collapse = document.getElementsByClassName("faq_collapse");
    var i;

    for (i = 0; i < faq_collapse.length; i++) {
        faq_collapse[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var tag = this.childNodes[0].childNodes[0];
        console.log(tag);
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
            content.style.display = "none";
            tag.classList.remove("fa-minus");
            tag.classList.add("fa-plus");
        } else {
            content.style.display = "block";
            tag.classList.add("fa-minus");
            tag.classList.remove("fa-plus");
        }
    });
    }
</script>