
<div class="specialized-banner">
    <?=$this->render('header.phtml')?>
</div>
<div class="specialized-title">
    <h2>Comparta sus recursos de información</h2>
</div>
<div id="information">
  <div class="row col-md-8">
    <form action="">
      <div class="col-md-6"> <label for="">Nombre completo:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"> <label for="">Correo electrónico:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"> <label for="">País:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"> <label for="">Departamento/Provincia:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"> <label for="">Nombre de la institución:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Sitio web de la institución:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Nombre de la biblioteca:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Sitio web de la biblioteca:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Nombre de la(s) plataformas:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Nombre del esquema de metadatos que utiliza:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Enlace(s) público(s):</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Enlace al protocolo de intercambio OAI-PMH u otro:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Opciones de exportación:</label>
      <input type="text" class="form-control"></div>
      <div class="col-md-6"><label for="">Comentario:</label>
      <input type="text" class="form-control"></div>

    </form>
  </div>
</div>





