<?php $this->headTitle('SIDALC'); ?>
<div class="specialized-banner">
    <?=$this->render('header.phtml')?>
</div>
<div class="specialized-title">
    <h2>Sobre SIDALC</h2>
</div>
<div class="about-sidalc">
    <p>
    El Instituto Interamericano de Cooperación para la Agricultura (IICA) y el Centro Agronómico Tropical de Investigación y Enseñanza (CATIE) reconocen que la gestión de la información y el compartir conocimientos son fundamentales para el mejoramiento de la agricultura y la vida rural en los países de América Latina y el Caribe (ALC). Ambos son insumos básicos para los procesos de mejora continua y toma de decisión, así como para el quehacer en los ámbitos de la educación, la capacitación, la innovación, la competitividad, el desarrollo sostenible y la seguridad alimentaria. 
    </p>
    <h3>¿Qué es la Alianza de Servicios de Información Agropecuaria en las Américas (SIDALC)? </h3>
    <p>
    El SIDALC es una alianza internacional de servicios información agrícola, pecuaria, forestal y ambiental, mediante el cual un importante grupo de instituciones de 22 países americanos comparten en red, su información y sus servicios. Creado en 1999, hoy constituye una de las ventanas del conocimiento explicito más importantes de ALC.  La puesta en operación del SIDALC fue posible gracias a una donación de la Fundación Kellogg, al liderazgo técnico que asumieron el IICA y el CATIE y a la participación de una importante cantidad de instituciones nacionales, regionales e internacionales.
    </p>
    <p>
    La alianza facilita el acceso a la información producida en el hemisferio que se encuentra debidamente organizada en bibliotecas y otros centros de información agrícola, pecuaria, ambiental, forestal y afines. Pone a disposición cerca de tres millones de materiales referenciales y más de 300 mil documentos a texto completo, entre ellos libros, revistas, tesis e informes. 
    </p>
    <p>
    Actualmente los servicios de la alianza SIDALC son de uso público, no requiere suscripción y puede ser utilizado por los usuarios mediante la dirección www.sidalc.net. Cerca de 25.000 consultas diarias se realizan en los buscadores en línea de las colecciones disponibles.  Además, el SIDALC integra otros sistemas de información agropecuaria, ambiental y forestal promovidos en diversos países americanos, los cuales permiten a los actores de la agricultura y los territorios rurales disponer de información y conocimientos pertinentes a esas áreas. 
    </p>
    <p>
    El éxito del SIDALC radica en que cuenta con el capital intelectual de al menos 178 instituciones y redes nacionales que, al fungir como intermediarios de la gestión y difusión de la información, amplían y modernizan permanentemente sus servicios frente a los nuevos paradigmas de la sociedad del conocimiento. Dentro de la alianza opera un servicio de intercambio científico, lo que ha permitido a cientos de bibliotecas acceder de manera oportuna a importantes recursos de información para sus usuarios. 
    </p>
    <p>
    El SIDALC hoy día, es el resultado de la evolución de diversas iniciativas dirigidas a la gestión del conocimiento y la información que lo antecedieron. Todas promovidas por el IICA, tales como la Biblioteca Conmemorativa Orton, fundada en 1943; el Servicio de Intercambio Científico (SIC), creado en 1958; la Asociación Interamericana de Bibliotecarios, Documentalistas y Especialistas en Información Agrícola (AIBDA), establecida en 1965; y el Sistema Interamericano de Información Agrícola (AGRINTER), creado en 1972. 
    </p>
    <h3> ¿Cómo opera el SIDALC? </h3>
    <p>
    El SIDALC funciona como una comunidad de especialistas en información agropecuaria, forestal y afín de diversas instituciones de las Américas interesadas en brindar servicios abiertamente, mediante lo cual construyen el círculo virtuoso de un consorcio colaborativo en que “cada una comparte un poco, para tener mucho entre todas”, conservando su identidad y manteniendo sus políticas de prestación y cobro de servicios especializados.
    </p>
    <p>
    Esa es precisamente la mayor ventaja competitiva del SIDALC, pues mediante un sistema de ámbito hemisférico, al que se vinculan más de 20 redes nacionales de información, permite el acceso a conocimientos especializados en agricultura y vida rural de las Américas y compartirlos a nivel mundial. Por otra parte, el SIDALC posibilita movilizar recursos humanos e informacionales entre países y regiones, a través de lo cual promueve y brinda apoyo a iniciativas nacionales en gestión de información, facilita el flujo de esta e impulsa la difusión y transferencia de experiencias exitosas. 
    </p>
    <h3> ¿Cuáles son los beneficios que el SIDALC ofrece? </h3>
    <ul>
        <li>Participación en el mayor servicio hemisférico de información especializada en agricultura y vida rural de las Américas. </li>
        <li>Vinculación a sistemas internacionales de información, requisito fundamental en los procesos de acreditación de la calidad de servicios institucionales, por ejemplo, de las carreras universitarias. </li>
        <li>Reconocimiento, tanto en el ámbito nacional como en el internacional, de las redes, bibliotecas y otros centros de información asociados. </li>
        <li>Incremento en la demanda de servicios de parte de los usuarios e impacto positivo en los servicios de referencia de las bibliotecas especializadas. </li>
        <li>Acceso a una colección mayor de recursos de información especializados en agricultura, ambiente, silvicultura y áreas afines: descubridor agropecuario, así como a la red de expertos. </li>
        <li>Acceso abierto a herramientas y metodologías para la gestión de información especializada, incluyendo diferentes cursos relacionados con estos temas. </li>
        <li>Respaldo internacional de los catálogos institucionales. </li>
        <li>Visibilidad a nivel global de las colecciones institucionales mediante SIDALC.NET y Google.com, sin que la institución pierda su identidad. </li>
        <li>Involucramiento en proyectos relacionados con la gestión de información para el agro. </li>
    </ul>
    <h3>¿Cuáles son los productos del SIDALC?</h3>
    <ul>
        <li>Una red de intercambio científico integrada por especialistas en gestión de la información dispuestos a atender sus consultas en forma pronta</li>
        <li>Un descubridor agropecuario, indizado desde Google, que contiene colecciones especializadas en agricultura, ambiente, silvicultura y áreas afines, con referencias y recursos electrónicos de toda índole: textos, materiales audiovisuales, entre otros. </li>
        <li>Un vínculo directo con la Biblioteca de Agricultura y la Red de Centros de Información AGNIC, ambos de Estados Unidos. </li>
        <li>El acceso a diversos sistemas de información agropecuarios, así como a centros de recursos y a paquetes especializados de información agrícola y rural de ALC. </li>
    </ul>
</div>