<div class="specialized-banner">
    <?=$this->render('header.phtml')?>
</div>
<div class="specialized-title">
    <h2>Recursos especializados</h2>
</div>
<div id="specialized">
    <div class="row col-md-12">
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Agricultura+familiar&type=AllFields&limit=20" rel="nofollow">
            Agricultura familiar  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Agua+para+la+agricultura&type=AllFields&limit=20" rel="nofollow">
            Agua para la agricultura  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Aguacate&type=AllFields&limit=20" rel="nofollow">
            Aguacate  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Arroz&type=AllFields&limit=20" rel="nofollow">
            Arroz  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Bambú&type=AllFields&limit=20" rel="nofollow">
            Bambú  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Bioinsumos&type=AllFields&limit=20" rel="nofollow">
            Bioinsumos  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Buenas+Prácticas+de+Producción&type=AllFields&limit=20" rel="nofollow">
            Buenas Prácticas de Producción  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Cacao&type=AllFields&limit=20" rel="nofollow">
            Cacao 
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Cambio+climático&type=AllFields&limit=20" rel="nofollow">
            Cambio climático  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Cooperativas+agrícolas&type=AllFields&limit=20" rel="nofollow">
            Cooperativas agrícolas  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Forestales&type=AllFields&limit=20" rel="nofollow">
            Forestales  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Forrajes&type=AllFields&limit=20" rel="nofollow">
            Forrajes  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Ganadería&type=AllFields&limit=20" rel="nofollow">
            Ganadería  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Género&type=AllFields&limit=20" rel="nofollow">
            Género 
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Juventud+rural&type=AllFields&limit=20" rel="nofollow">
            Juventud rural  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Mujer+rural&type=AllFields&limit=20" rel="nofollow">
            Mujer rural  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Papa&type=AllFields&limit=20" rel="nofollow">
            Papa  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Producción+lechera&type=AllFields&limit=20" rel="nofollow">
            Producción lechera 
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Quinua&type=AllFields&limit=20" rel="nofollow">
            Quinua  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Roya+del+café&type=AllFields&limit=20" rel="nofollow">
            Roya del café  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Saberes+locales&type=AllFields&limit=20" rel="nofollow">
            Saberes locales  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Seguridad+alimentaria&type=AllFields&limit=20" rel="nofollow">
            Seguridad alimentaria  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Tomate&type=AllFields&limit=20" rel="nofollow">
            Tomate  
          </a>
        </div>
       <div class="col-md-2">
          <a href="/vufind/Search2/Results?lookfor=Yuca&type=AllFields&limit=20" rel="nofollow">
            Yuca  
          </a>
        </div>
       <div class="col-md-2">
          <a href='/vufind/Search2/Results?lookfor=&type=AllFields&filter%5B%5D=format%3A"Thesis"' rel="nofollow">
          Tesis  
          </a>
        </div>
    </div>
  
</div>