<?php $alt = $this->link ? trim($this->driver->tryMethod('getTitle') ?? '') : ''; ?>
<?php if ($this->link && !empty($alt)): ?><a href="<?=$this->escapeHtmlAttr($this->link)?>" class="record-cover-link"><?php endif; ?>
<?php /* Display thumbnail if appropriate: */ ?>

<?php if ($cover): ?>
  <!-- <img src="<?=$this->escapeHtmlAttr($cover); ?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="<?=$this->escapeHtmlAttr($alt); ?>" /> -->
<?php elseif ($cover === false): ?>
  <img src="<?=$this->url('cover-unavailable')?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="" />
<?php else: ?>
  <div class="ajaxcover">
    <div class="spinner"><?=$this->icon('spinner') ?> <?=$this->translate('Loading')?>...</div>
    <div class="cover-container">
      <img <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>data-context="<?=$this->escapeHtmlAttr($this->context)?>" data-recordsource="<?=$this->escapeHtmlAttr($driver->getSourceIdentifier())?>" data-recordid="<?=$this->escapeHtmlAttr($driver->getUniqueID())?>" data-coversize="<?=$this->escapeHtmlAttr($size)?>" class="recordcover ajax" alt="<?=$this->escapeHtmlAttr($alt); ?>" />
    </div>
  </div>
<?php endif; ?>
<?php if ($this->link && !empty($alt)): ?></a><?php endif; ?>

<?php
$imageRec="/vufind/themes/root/images/noCover2.gif";
foreach ($this->driver->getComponent() as $available){
  // cursos (moodle), bibliográfico (bibliotecas y repositorios), revistas, perfiles profesionales (VIVO), datos de investigación (repositorios de datos)
  switch ($available) {
    case "Bibliográfico":
      $imageRec="/vufind/themes/bootstrap3/images/libros.png";
        break;
    case "Revista":
      $imageRec="/vufind/themes/bootstrap3/images/revista.png";
        break;
    case "perfil":
      $imageRec="/vufind/themes/bootstrap3/images/perfil.png";
        break;
    case "curso":
      $imageRec="/vufind/themes/bootstrap3/images/cursos.png";
          break;
    case "datos":
      $imageRec="/vufind/themes/bootstrap3/images/datos.png";
          break;
}
}    
 ?>
 <img src="<?=$imageRec?>"  <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="<?=$this->escapeHtmlAttr($alt); ?>" />

