<?php foreach ($data as $field): ?>

    
    <?php $subject = ''; ?>
    <?php if(count($field) == 1) $field = explode('--', $field[0]); ?>
    <?php $i = 0; foreach ($field as $subfield): ?>
      <?=($i++ == 0) ? '' : ' &gt; '?>
      <?php $subject = trim($subject . ' ' . $subfield); ?>
      <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow" target="_blank"><?=trim($this->escapeHtml($subfield))?></a>,
    <?php endforeach; ?>
    

<?php endforeach; ?>
